# Generated by Django 2.2.1 on 2019-06-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(default='yourname', max_length=100),
            preserve_default=False,
        ),
    ]
