# Generated by Django 2.2.1 on 2019-07-11 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnId', models.CharField(max_length=64, verbose_name='TXNID')),
                ('bankTxnId', models.CharField(max_length=100, verbose_name='BANKTXNID')),
                ('orderId', models.CharField(max_length=50, verbose_name='ORDERID')),
                ('txnAmount', models.CharField(max_length=10, verbose_name='TXNAMOUNT')),
                ('status', models.CharField(max_length=20, verbose_name='STATUS')),
                ('txnType', models.CharField(max_length=5, verbose_name='TXNTYPE')),
                ('respCode', models.CharField(max_length=10, verbose_name='RESPCODE')),
                ('respMsg', models.CharField(max_length=500, verbose_name='RESPMSG')),
                ('mid', models.CharField(max_length=20, verbose_name='MID')),
                ('refundAmt', models.CharField(max_length=10, verbose_name='REFUNDAMT')),
                ('txnDate', models.DateTimeField(verbose_name='TXNDATE')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_success',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnId', models.CharField(max_length=64, verbose_name='TXNID')),
                ('bankTxnId', models.CharField(max_length=100, verbose_name='BANKTXNID')),
                ('orderId', models.CharField(max_length=50, verbose_name='ORDERID')),
                ('txnAmount', models.CharField(max_length=10, verbose_name='TXNAMOUNT')),
                ('status', models.CharField(max_length=20, verbose_name='STATUS')),
                ('txnType', models.CharField(max_length=5, verbose_name='TXNTYPE')),
                ('gatewayName', models.CharField(max_length=15, verbose_name='GATEWAYNAME')),
                ('respCode', models.CharField(max_length=10, verbose_name='RESPCODE')),
                ('respMsg', models.CharField(max_length=500, verbose_name='RESPMSG')),
                ('bankName', models.CharField(max_length=500, verbose_name='BANKNAME')),
                ('mid', models.CharField(max_length=20, verbose_name='MID')),
                ('paymentMode', models.CharField(max_length=15, verbose_name='PAYMENTMODE')),
                ('refundAmt', models.CharField(max_length=10, verbose_name='REFUNDAMT')),
                ('txnDate', models.DateTimeField(verbose_name='TXNDATE')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, verbose_name='CURRENCY')),
                ('gatewayName', models.CharField(max_length=15, verbose_name='GATEWAYNAME')),
                ('respMsg', models.CharField(max_length=500, verbose_name='RESPMSG')),
                ('bankName', models.CharField(max_length=500, verbose_name='BANKNAME')),
                ('paymentMode', models.CharField(max_length=15, verbose_name='PAYMENTMODE')),
                ('mid', models.CharField(max_length=20, verbose_name='MID')),
                ('respCode', models.CharField(max_length=10, verbose_name='RESPCODE')),
                ('txnId', models.CharField(max_length=64, verbose_name='TXNID')),
                ('txnAmount', models.CharField(max_length=10, verbose_name='TXNAMOUNT')),
                ('orderId', models.CharField(max_length=50, verbose_name='ORDERID')),
                ('status', models.CharField(max_length=20, verbose_name='STATUS')),
                ('bankTxnId', models.CharField(max_length=100, verbose_name='BANKTXNID')),
                ('txnDate', models.DateTimeField(verbose_name='TXNDATE')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngo.Ngo', verbose_name='to_ngo')),
                ('payment_error', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment.Payment_error', verbose_name='payment_error')),
                ('payment_success', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment.Payment_success', verbose_name='payment_success')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
