# Generated by Django 2.2.1 on 2019-07-01 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='transaction_id')),
                ('transaction_time', models.DateTimeField(auto_now_add=True, verbose_name='transaction_time')),
                ('payment_status', models.BooleanField(default=False, verbose_name='payment_status')),
                ('amount_transacted', models.IntegerField(default=1, verbose_name='amount_funded')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngo.Ngo', verbose_name='to_ngo')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
