# Generated by Django 2.2.1 on 2019-07-11 07:17

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ngo',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(choices=[('AGC', 'Age care (care for the aged/Older persons)'), ('AGR', 'Agriculture'), ('AW', 'Animal Welfare'), ('ANC', 'Art & Craft'), ('CE', 'Child Education'), ('CUD', 'Cities/Urban Development'), ('CD', 'Community Development'), ('CNH', ' Culture & Heritage'), ('D', 'Disability'), ('DM', 'Disaster Management'), ('EDU', 'Education'), ('ENVI', 'Environmental issues'), ('HNH', 'Health & Hygiene'), ('HA', ' HIV/AIDS'), ('HS', 'Housing & Slums'), ('P', 'Population'), ('PR', 'Poverty Removal'), ('RD', 'Rural Development'), ('STD', 'Science & Technology Development'), ('TP', 'Tribal people'), ('WM', 'Waste Management'), ('DW', 'Drinking Water'), ('WO', 'Women'), ('O', 'others')], max_length=50, verbose_name='category')),
                ('ngo_name', models.CharField(max_length=50, verbose_name='ngo_name')),
                ('Email', models.EmailField(max_length=254, unique=True, verbose_name='email_ngo')),
                ('Ngo_certificate', models.URLField(default='https://www.google.com')),
                ('Ngo_website', models.URLField(default='https://www.google.com')),
            ],
            options={
                'verbose_name': 'Ngo',
                'verbose_name_plural': 'Ngos',
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='www.google.com', upload_to='profile_pics')),
                ('amount_collected', models.IntegerField(default=0)),
                ('long_description', models.TextField()),
                ('location', models.TextField()),
                ('goal', models.TextField(max_length=1000)),
                ('contact', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='contact_number')),
                ('Ngo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ngo.Ngo')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
