# Generated by Django 2.2.1 on 2019-07-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('users', '0001_initial'),
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='users',
            field=models.ManyToManyField(through='payment.Payment', to='users.user', verbose_name='users_to_ngo_through_payment'),
        ),
    ]
