# Generated by Django 2.2.1 on 2019-07-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_ngo_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='category',
            field=models.CharField(choices=[('AGC', 'Age care (care for the aged/Older persons)'), ('AGR', 'Agriculture'), ('AW', 'Animal Welfare'), ('ANC', 'Art & Craft'), ('CE', 'Child Education'), ('CUD', 'Cities/Urban Development'), ('CD', 'Community Development'), ('CNH', ' Culture & Heritage'), ('D', 'Disability'), ('DM', 'Disaster Management'), ('EDU', 'Education'), ('ENVI', 'Environmental issues'), ('HNH', 'Health & Hygiene'), ('HA', ' HIV/AIDS'), ('HS', 'Housing & Slums'), ('P', 'Population'), ('PR', 'Poverty Removal'), ('RD', 'Rural Development'), ('STD', 'Science & Technology Development'), ('TP', 'Tribal people'), ('WM', 'Waste Management'), ('DW', 'Drinking Water'), ('WO', 'Women'), ('O', 'others')], default='RD', max_length=50, verbose_name='category'),
            preserve_default=False,
        ),
    ]
